<?php
/**
 * Created by PhpStorm.
 * User: Diego
 * Date: 2/2/2019
 * Time: 12:18 AM
 */

require __DIR__ .'/../vendor/autoload.php';
require_once 'resources/secrets.php';

$bot_pool = [
    'A Bot of Ice and Fire',
    'Art Automata',
    'ArtPostbot1519',
    'BabelBot 5000',
    'BartenderBot 1862',
    'Ben Garrison Bot 1980',
    'BiblepostBot 1111',
    'BlessedBot 6009',
    'Botbot 1000',
    'BotoB 8008',
    'Botstradamus 1555',
    'Bots of New York',
    'BottomText 5000 v2.0',
    'BurgerBot 4545',
    'BusinessBot 500',
    'Cardsagainstbot',
    'Cards Against Humanity Bot',
    'Cdl Battle Bot',
    'CensorBot 1111',
    'CommentBot 2005',
    'CopypastaBot 234',
    'CountryBot 0208',
    'CraftingBot 64',
    'Create-A-Wrestler Bot 2002',
    'Creepypasta bot',
    'CyanideBot69',
    'DestinyBot3000',
    'DictionaryPostbot',
    'Divmeterbot_FG204',
    'Dungeon Post Bot 1974',
    'ElementBot 9654',
    'EmojiBot 101',
    'Encarta95PostBot',
    'Every Tom and Jerry Frame in Order',
    'FactpostBot4286',
    'Feijoada Simulator v2.0.0',
    'FibonacciBot1618',
    'Fighter Bot 420',
    'Floor-Plan-Bot2521',
    'Foreign Lands ロボット',
    'FriendlyBot',
    'FunnyPost Bot 5000',
    'GamerTime Bot 420',
    'Garkov PostBot 1978',
    'GoldenratioBot 1.618',
    'GreentextBot',
    'HoroscopeBot 12',
    'HungerGamesBot 74',
    'IdeaBot 5200',
    'IslandBot 1620',
    'ImagineBot 2070',
    'InspiroBot Quotes',
    'InspiroBot.me',
    'JailBot 68',
    'JailBot 69',
    'Jewishnamebot5779',
    'Kino Bot 1968',
    'Kino Bot 1969',
    'LawBot64',
    'LawnmowerBot',
    'LiveBot 2: Electric Boogaloo',
    'Lolmatchup Bot 2009',
    'LossBot 12250',
    'MathsBot 271828',
    'MillennialBot 2019',
    'MelodyBot3456',
    'Namebot 1372',
    'NewsBot1926',
    'NothingPostBot 0000',
    'Orange Soapstone Bot 259+301',
    'OutfitBot7623',
    'PaintBot',
    'PaletteBot',
    'PCBuilderBot 1975',
    'PerrisimaBot 5000',
    'Pie Chart Bot 45%',
    'PizzaBot',
    'Pokébot Red',
    'PokéFusionBot 1996',
    'PokéTeamBot 151',
    'Pot of Greed Everyday',
    'Psychedelic Post Bot 1337',
    'Pub Chem Bot 6.022',
    'Ragecomicbot 2010',
    'Random Color Memes II: Electric Bluegaloo',
    'Ratherbot 1111',
    'Russian Roulette Bot 1667',
    'SbeveBot 14',
    'ScheduleBot 79014',
    'Scriptbot 1902',
    'SelfieBot9004',
    'Shirtpostbot 2300',
    'ShitpostBot 5000',
    'ShippBot1321',
    'ShowerthoughtsBot 1981',
    'Slotmachine bot 777',
    'SmileyBot 2305',
    'StandBot4444',
    'StreetViewBot 5000 v2.0',
    'SztukapostBot2044',
    'Text2SpeechBot 0010',
    'Thanos Bot Thanos Bot',
    'TinderBot 225',
    'ToolpostBot',
    'TrackMania Trackpostbot 2004',
    'Travel Bot 195',
    'Two Emoji',
    'Uranometriabot 1603',
    'Vidya Game Bot 1337',
    'VennDiagram Bot 1111',
    'VortessenceBot 2.0',
    'WeatherBot 5000',
    'Whipnaenaebot 2015',
    'WikipostBot 5000',
    'Web MD Bot',
    'WorldWarBot 2020',
    'WWII PostBot 1939',
    'Every Ed, Edd n Eddy Frame In Order',
    'Every Frame Of Shrek In Order',
    'Every Simpsons Frame in Order',
    'Every Frame Of The Powerpuff Girls In order',
    'Every Tom and Jerry Frame in Order',
    'Every “Star War: Backstroke of the West” Frame In Order',
    'CowManglerBot 5000',
    'DeathgripsBot 5000',
    'EvangelionBot 5000',
    'JermaBot 5985',
    'JojoPostBot 5000',
    'PerhapsBot 5000',
    'RPB: Posting Bot',
    'SentiencePostBot 5000',
    'Shitposthony Botano',
    'SpongepostBob 5000',
    'TestpostBot 5000',
    'Weeabot 5000',
    'CivilWarBot 2020',
    'Guerra Civil Brasileira Bot',
    'Interplanetary War Bot XXII',
    'ItaliaGuerraBot 2020',
    'Philippine Ethnolinguistic Warbot 2020',
    'A random texture from minecraft until all have been posted and then i die',
    'A cursed image every half an hour',
    'A Peashooter but each half-an-hour has a random letter until it is sentient',
    'AcronymBot0000',
    'AlbumBot 808',
    'AlbumGenerator420',
    'AnagramBot0009',
    'BezierPostBot 0000',
    'Bot Idea: A Bot That Posts Bot Ideas',
    'BottomText 5000',
    'BuzzfeedQuiz Bot 2006',
    'ChefBot1949',
    'ChessBot 1951',
    'ChristianMom Bot 1542',
    'Colormachine',
    'Content Aware Bot',
    'CricketBot 1909',
    'DadsGoοgləHistoryBot 3000',
    'DeviantBot 7245',
    'Diseasepostbot 1665',
    'DogePost Bot 1619',
    'DogpostBot',
    'ElektronischeBot8888',
    'FaceswapBot 6656',
    'Failarmynot 0000',
    'FMKbot',
    'Frequently Bot 1995',
    'HankBot0419307',
    'ImposterBot Pmc2963468',
    'Inspirobot',
    'OreoBot 1912',
    'PajeetBot 2021',
    'PHCommentBot',
    'Polishpostbot',
    'QuoteshitBot',
    'REDACTEDHowBot 5000',
    'ScheduleBot 79014',
    'SpilledInk Bot 42',
    'Styletransferbot9683',
    'TextpostBot 98',
    'Undergroundyoutubebot 0001',
    'US Election Bot 1776',
    'VsauceBot Here',
    'WordpostBot'
];

$dt = new BotPostBot\DataLogger();

$result = array(
    'image' => '',
    'title' => '',
    'bot_link' => '',
    'comment' => ''
);

// Make post with any random image
$FB_helper = new BotPostBot\FacebookHelper();
$fb = $FB_helper->init($_APP_ID, $_APP_SECRET, $_ACCESS_TOKEN_DEBUG);

$message = 'posting...';
$dt->logdata($message);

$FB_helper->newPost($fb, $result['image'], $result['title'], $result['bot_link'], $result['comment']);
