<?php
/**
 * Created by PhpStorm.
 * User: Diego
 * Date: 3/1/2019
 * Time: 12:21 AM
 */

require __DIR__ .'/../vendor/autoload.php';
require_once 'resources/secrets.php';

$aux_name_link_description = array(
    0 => array('A Bot of Ice and Fire', 'https://www.facebook.com/pg/ABotOfIceAndFire-392321551380863', 'Posts a sentence in the style of the Game of Thrones books every 30 minutes.'),
    1 => array('Art Automata', 'https://www.facebook.com/artautomata', 'Randomly generated abstract art.'),
    2 => array('ArtPostbot1519', 'https://www.facebook.com/ArtpostBot/', 'Random (dye house) painting every 60 minutes.'),
    3 => array('BabelBot 5000', 'https://www.facebook.com/babelbot5000/', 'posts excerpts from books found in the library of babel'),
    4 => array('BartenderBot 1862', 'https://www.facebook.com/bartenderbot1862/', 'Welcome to Bot\'s Tavern! Each hour BartenderBot will mix and serve you a new drink. Cheers! (please drink responsibly)'),
    5 => array('Ben Garrison Bot 1980', 'https://www.facebook.com/RealBenGarrison/', 'This is a very simple bot which places random nouns at random locations on a random image.'),
    6 => array('BiblepostBot 1111', 'https://www.facebook.com/BiblepostBot-1111-2017448901882151/', 'A bot that puts random Bible quotes on random anime pictures.'),
    7 => array('BlessedBot 6009', 'https://www.facebook.com/BlessedBot/', 'Bot that posts a random image sourced from www.reddit.com/r/blessedimages/'),
    8 => array('Botbot 1000', 'https://www.facebook.com/botbot1k/', 'Comes up with random bot ideas'),
    9 => array('BotoB 8008', 'https://www.facebook.com/botob8008/?ref=br_rs', 'A bot that takes random SPB source images and flips them horizontally across their centre'),
    10 => array('Botstradamus 1555', 'https://www.facebook.com/Botstradamus1555/', 'Randomly generated predictions about well known people'),
    11 => array('Bots of New York', 'https://www.facebook.com/botsofnewyork', 'This bot is a parody of Humans of New York. It uses various machine-learning and computer vision programs to generate images of imaginary people and pairs them with captions generated based on the Humans of New York captions corpus.'),
    12 => array('BottomText 5000 v2.0', 'https://www.facebook.com/BOTtomtext5k/?ref=br_rs', 'BottomText 5000 backup page'),
    13 => array('BurgerBot 4545', 'https://www.facebook.com/BurgerBot4545/', 'This bot randomly generates burgers!'),
    14 => array('BusinessBot 500', 'https://www.facebook.com/BusinessBot-500-271204917088261/', 'Here at BusinessBot, we like to provide invaluable insight into the world of business. With our specialized algorithm, which is what we like to call making stuff up using random words, we try our hardest to provide business names, slogans, and what service to provide at what cost.'),
    15 => array('Cardsagainstbot', 'https://www.facebook.com/cardsagainstrobot/', 'Completely bot generated CAH card combos. Every half hour no less. Made by some kid in 3 days, so if I can do it so can you god bless.'),
    16 => array('Cards Against Humanity Bot', 'https://www.facebook.com/Cards-Against-Humanity-Bot-1814266302010827/', 'Posts a random Cards Against Humanity combination'),
    17 => array('Cdl Battle Bot', 'https://www.facebook.com/cdlbattle/', 'A simple bot that simulate a hypothetical battle between italian\'s degree courses'),
    18 => array('CensorBot 1111', 'https://www.facebook.com/CensorBot-1111-227202038206959/', 'A bot that takes a random image (from SPB sources) and censors a random part of it.'),
    19 => array('CommentBot 2005', 'https://www.facebook.com/commentbot2005/', 'A bot that posts a random comment from a random YouTube video every hour'),
    20 => array('CopypastaBot 234', 'https://www.facebook.com/CopypastaBot-234-727669200962237/', 'This bot uses Markov Chains to generate random copypastas. I used a selection of copypastas from r/copypastas as the source, however, I\'m always looking for new pastas! Please post as many as you can as a comment to this post. The more obscure and irrelevant, the better!'),
    21 => array('CountryBot 0208', 'https://www.facebook.com/countrybot208/', 'A bot that makes random words by getting random letters from random countries'),
    22 => array('CraftingBot 64', 'https://www.facebook.com/CraftingBot64/', 'CraftingBot 64 is here to come up with some wacky recipes that dont make sense 99% of the time using Minecraft assets.'),
    23 => array('Create-A-Wrestler Bot 2002', 'https://www.facebook.com/CAWBot2003/', 'Randomly generated CAWs from the classic game Smackdown! Here Comes The Pain. Royal Rumbles and Title matches every 30 characters generated!'),
    24 => array('Creepypasta bot', 'https://www.facebook.com/creepypastabot/', 'A bot that randomly generates scary stories by drawing from a database of creepypasta.'),
    25 => array('CyanideBot69', 'https://www.facebook.com/cyanidebot69/', 'Posts comics generated at explosm.net/rcg'),
    26 => array('DestinyBot3000', 'https://www.facebook.com/DestinyBot3000', 'One day, Billie Eilish was walking outside and she saw a boy crying. She said to him ‘Here kid, have a roll of Air Conditioning Pair Coil 1/4\' x 3/8\' 410A 20m Polyethylene UV protected insulated Copper heat resistant to 120C. You\'re destined to do great things.’ That boy was Elon Musk.'),
    27 => array('DictionaryPostbot', 'https://www.facebook.com/dictionarypostbot/', 'Automatically posting random (sometimes unreadable) definition from UrbanDictionary every 15 minutes with occasional downtimes.'),
    28 => array('Divmeterbot_FG204', 'https://www.facebook.com/divmeterbot/', 'Divergence meter bot inspired by Steins'),
    29 => array('Dungeon Post Bot 1974', 'https://www.facebook.com/dungeonpostbot/', 'This bot will post D&D stories generated automatically'),
    30 => array('ElementBot 9654', 'https://www.facebook.com/elementbot9654/', 'A bot that posts a random string of element symbols every hour.'),
    31 => array('EmojiBot 101', 'https://www.facebook.com/emojibot101/?ref=br_rs', 'bot that posts random emojis once an hour'),
    32 => array('Encarta95PostBot', 'https://www.facebook.com/encarta95postbot/', 'Twice a day, a random Encarta \'95 article, for the next 35 years.'),
    33 => array('Every Tom and Jerry Frame in Order', 'https://www.facebook.com/tomandjerrybot/', 'Posts all the frames of episodes of Tom and Jerry, one at a time in sequential order'),
    34 => array('FactpostBot4286', 'https://www.facebook.com/FactpostMarkov/', 'FactpostBot randomly generates a fact using markov chains, and tries to source a relevant background image from google to post with the fact.'),
    35 => array('Feijoada Simulator v2.0.0', 'https://www.facebook.com/Feijoada-Simulator-v200-258433244715394/', 'huehuehue'),
    36 => array('FibonacciBot1618', 'https://www.facebook.com/fibonaccibot/', 'F(0) = F(1) = 1'),
    37 => array('Fighter Bot 420', 'https://www.facebook.com/FighterBot420/', 'A bot that imitates fighting games like Tekken, Mortal Kombat etc. by running a championship of 100 fighters that goes 1v1 until there’s only a single fighter left.'),
    38 => array('Floor-Plan-Bot2521', 'https://www.facebook.com/floorplanbot/', 'We make the best floor plans for everyone. Like our page to get floor plans for your future homes.'),
    39 => array('Foreign Lands ロボット', 'https://www.facebook.com/TheseForeignLandsBot/', 'Join me, as we explore these Foreign Lands.'),
    40 => array('FriendlyBot', 'https://www.facebook.com/FriendlyBot5335/', 'I make art out of social networks.'),
    41 => array('FunnyPost Bot 5000', 'https://www.facebook.com/funnypostbot/', 'posts a picture from the SPB database witch a caption obtained from those picture files'),
    42 => array('GamerTime Bot 420', 'https://www.facebook.com/GamerTimeBot420/', 'Beep Boop I post random gamer time quotes.'),
    43 => array('Garkov PostBot 1978', 'https://www.facebook.com/garkovpostbot/', 'bot that posts comics from http://joshmillard.com/garkov/once every two hours'),
    44 => array('GoldenratioBot 1.618', 'https://www.facebook.com/GoldenratioBot1.618', 'Superimposes various fibonacci spirals onto random (and user submitted) images. This bot is a parody of the trendy and misappropriated usage of the golden ratio and fibonacci spiral to “explain” why something is objectively beautiful.'),
    45 => array('GreentextBot', 'https://www.facebook.com/GreentextBot/', 'Doot Doot. I\'m a bot that makes amazingly realistic greentexts.'),
    46 => array('HoroscopeBot 12', 'https://www.facebook.com/horoscopebot12.0/', 'posts randomly generated horoscopes'),
    47 => array('HungerGamesBot 74', 'https://www.facebook.com/hungergamesbot74/', 'picks 36 random people and pits them against each other in the Hunger Games'),
    48 => array('IdeaBot 5200', 'https://www.facebook.com/IdeaBot5200/', 'Posts ideas'),
    49 => array('IslandBot 1620', 'https://www.facebook.com/islandbot/', 'This bot generates a random islands twice a day.'),
    50 => array('ImagineBot 2070', 'https://www.facebook.com/imaginebot2070/', 'essentially generates and posts “Imagine [insert random thing here]” every 6 hours.'),
    51 => array('InspiroBot Quotes', 'http://inspirobot.me/https://www.facebook.com/InspiroBotQuotesIGot/', 'Not affiliated with InspiroBot, just posting stuff that I got from it. InspiroBot website:'),
    52 => array('InspiroBot.me', 'https://www.facebook.com/InspiroBot/', 'An artificial intelligence dedicated to generating unlimited amounts of unique inspirational quotes for endless enrichment of pointless human existence.'),
    53 => array('JailBot 68', 'https://www.facebook.com/JailBot-68-2074652775983520/', 'JailBot 69 backup page'),
    54 => array('JailBot 69', 'https://www.facebook.com/JailBot-69-404741493625118/', 'Gives a random person a random punishment'),
    55 => array('Jewishnamebot5779', 'https://www.facebook.com/BatshevaEhrman/', 'generates random Jewish names'),
    56 => array('Kino Bot 1968', 'https://www.facebook.com/Kino-Bot-1968-258743395015701/', 'Bot that automatically generates movie opinions.'),
    57 => array('Kino Bot 1969', 'https://www.facebook.com/Kino-Bot-1969-839429566425589/', 'Kino Bot 1969 backup page'),
    58 => array('LawBot64', 'https://www.facebook.com/LawBot64/', 'LawBot64 is an automatic bot created in C# designed to generate weird laws, sentences and images based on a large SQL database of verbs and items. It will also assign the law to a country and generate a penalty all completely at random. It will post a new law or sentence every hour'),
    59 => array('LawnmowerBot', 'https://www.facebook.com/lawnmowerbot1/', 'I noticed that each lawnmower has such an distinct design that they are bound to have different, concrete characters. So by giving them names and nicknames we can assing them a personality they so very much deserve.'),
    60 => array('LiveBot 2: Electric Boogaloo', 'https://www.facebook.com/realLiveB0t/', 'Official LiveBot Schedule: Every weekend, anytime between 3PM and 8PM EST.'),
    61 => array('Lolmatchup Bot 2009', 'https://www.facebook.com/Lolmatchup-Bot-2009-2077647872353680/', 'Every 10 minutes, Blitzcrank will post a League of Legends team composition complete with its roles. Not recommended for competitive games.'),
    62 => array('LossBot 12250', 'https://www.facebook.com/lossbot12250/', 'This is a bot that randomly draws lines in an attempt to make the Loss meme.'),
    63 => array('MathsBot 271828', 'https://www.facebook.com/mathsbot271828/', 'Generating random maths questions one step at a time'),
    64 => array('MillennialBot 2019', 'https://www.facebook.com/MillenialsAreRuiningBots/', 'This is a bot made due to internet journalism claiming millennials are ruining X.'),
    65 => array('MelodyBot3456', 'https://www.facebook.com/MelodyBot3456-293565591327666/', 'Posts a randomly generated 8 bar melody once an hour.'),
    66 => array('Namebot 1372', 'https://www.facebook.com/Namebot1372/', 'posts awful names every hour I think'),
    67 => array('NewsBot1926', 'https://www.facebook.com/NewsBot1926/', 'We bring you the latest satire news headlines generated by a bot using artificial intelligence.'),
    68 => array('NothingPostBot 0000', 'https://www.facebook.com/nothingpostbot/', ''),
    69 => array('Orange Soapstone Bot 259+301', 'https://www.facebook.com/orangsoap/', 'try finger but hole'),
    70 => array('OutfitBot7623', 'https://www.facebook.com/outfitbot7623/', 'We make outfits for you to remember your occasions in the best (or worst) way possible!'),
    71 => array('PaintBot', 'https://www.facebook.com/paintbotv1/', 'This is PaintBot, a bot that draws random shapes on a random canvas and posts the result here once every 2 hours'),
    72 => array('PaletteBot', 'https://www.facebook.com/palettebot/', 'This bot downloads a random image from either unsplash or picsum, then scales it down, picks out 6 colors and posts them here.'),
    73 => array('PCBuilderBot 1975', 'https://www.facebook.com/PCBuilderBot-1975-2082149325225259/', 'Welcome to PCBuilderBot\'s PC Shop! Whether you\'re looking for a simple internet machine or a top-end rig, we\'ve got you covered! Every hour (on the 5th minute) I\'ll build a new computer and post it here! Or a pile of parts! It\'ll be fun!'),
    74 => array('PerrisimaBot 5000', 'https://www.facebook.com/perrisimabot/', 'Memes generados aleatoriamente'),
    75 => array('Pie Chart Bot 45%', 'https://www.facebook.com/piechartbot/', 'A bot that posts a random pie chart every half an hour and sometimes even does it right.'),
    76 => array('PizzaBot', 'https://www.facebook.com/pizzabot55/', 'This bot posts a randomly generated pizza every hour.'),
    77 => array('Pokébot Red', 'https://www.facebook.com/pokebotred/', 'This bot let\'s you play an interactive game of Pokémon.'),
    78 => array('PokéFusionBot 1996', 'https://www.facebook.com/pokefusionbot/', 'Hello there! Welcome to the wonderful world of Pokémon! You can call me the Professor -- my specialty is in splicing the DNA of Pokémon to create exciting hybrids!'),
    79 => array('PokéTeamBot 151', 'https://www.facebook.com/Pkmnteambot/', 'A bot who creates a random Pokémon team with its Pokémon, role, item and nature, any recommendation, message me. [dead until the admin can make another token]'),
    80 => array('Pot of Greed Everyday', 'https://www.facebook.com/Pot-of-Greed-Everyday-404151480379603/', 'the game'),
    81 => array('Psychedelic Post Bot 1337', 'https://www.facebook.com/1337botpost/', 'bot that post randomly generated psychedelic images once every two hours'),
    82 => array('Pub Chem Bot 6.022', 'https://www.facebook.com/Pub-Chem-Bot-6022-1188121881361493/', 'bot that posts random chemicals from PubChem'),
    83 => array('Ragecomicbot 2010', 'https://www.facebook.com/ragecomicbot2010/', 'A trip to the past.'),
    84 => array('Random Color Memes II: Electric Bluegaloo', 'https://www.facebook.com/randomcolormemes/', 'we post a random color every hour, which can also include gradients of 2, 3 or even 4 colors. Each post has a comment with some additional information about the color/s used (including some technical information and trivia).'),
    85 => array('Ratherbot 1111', 'https://www.facebook.com/Ratherbot-1111-619174248513666/', 'A bot that posts very interesting questions.'),
    86 => array('Russian Roulette Bot 1667', 'https://www.facebook.com/RussianRouletteBot1667/', 'interactive Russian roulette bot'),
    87 => array('SbeveBot 14', 'https://www.facebook.com/sbevebot14/', 'This is a bot that generates a random sentence from a Markov chain, then puts parentheses around random letters to try and create a "double meaning".'),
    88 => array('ScheduleBot 79014', 'https://www.facebook.com/ScheduleBot79014/', 'A bot that randomly choose an hour and an activitie to do during the day.'),
    89 => array('Scriptbot 1902', 'https://www.facebook.com/scriptbot1902/', 'A bot that generates screenplay scenes using Markov chains.'),
    90 => array('SelfieBot9004', 'https://www.facebook.com/SelfieBot9004/', 'Bringing together the #selfie of the internet'),
    91 => array('Shirtpostbot 2300', 'https://www.facebook.com/spb2300/', 'A bot that randomly generates really specific targeted T-shirts.'),
    92 => array('ShitpostBot 5000', 'https://www.facebook.com/shitpostbot5k/', 'the granddaddy of our great bot society'),
    93 => array('ShippBot1321', 'https://www.facebook.com/Shippbot/', 'A bot who posts a random shipp every time the admin wants. [dead until the admin can make another token]'),
    94 => array('ShowerthoughtsBot 1981', 'https://www.facebook.com/ShowerthoughtsBot/', 'generates “showerthoughts” by drawing from the r/Showerthoughts subreddit'),
    95 => array('Slotmachine bot 777', 'https://www.facebook.com/Slotmachine-bot-777-370461346888311/', 'A bot that plays slot machine every hour.'),
    96 => array('SmileyBot 2305', 'https://www.facebook.com/sbot2305/', 'A bot which randomly combines components of a growing range of emojis and attempts to name them in a legible manner.'),
    97 => array('StandBot4444', 'https://www.facebook.com/standbot4444/', 'A bot that generates Stands similar to the ones in the Jojo\'s Bizarre Adventure manga & anime series'),
    98 => array('StreetViewBot 5000 v2.0', 'https://www.facebook.com/streetviewbot/', 'posts pictures from Google street view'),
    99 => array('SztukapostBot2044', 'https://www.facebook.com/SztukapostBot/', 'ArtPostbot1519 backup page'),
    100 => array('Text2SpeechBot 0010', 'https://www.facebook.com/t2sbot/', 'interactive bot that does text to speech of the previous post’s top comment'),
    101 => array('Thanos Bot Thanos Bot', 'https://www.facebook.com/ThanosBotThanosBot/', 'This bot randomly blocks (snaps) people who comment (not replies though) on the pinned post'),
    102 => array('TinderBot 225', 'https://www.facebook.com/tinderbot225/', 'Welcome to TinderBot, the bot that generates random profiles for people that don\'t exist. The bot generates bio thanks to Markov chains based on user submitted bios. You can submit yours here : https://forms.gle/hWZX92X8GD18MZxYA'),
    103 => array('ToolpostBot', 'https://www.facebook.com/ToolpostBot/', 'shitpostbot 5000 except better'),
    104 => array('TrackMania Trackpostbot 2004', 'https://www.facebook.com/TMXBot/', 'posts random tracks from Track Mania'),
    105 => array('Travel Bot 195', 'https://www.facebook.com/TravelBot195/', 'A bot that choose a country to travel on and prepares the luggages!'),
    106 => array('Two Emoji', 'https://www.facebook.com/twoemoji/', 'Inspirational quotes and "Be the change you wish to see in the world" but the words "change" and "world" replaced with randomly selected emoji characters. It\'s art (kinda). Only posts automagically every morning.'),
    107 => array('Uranometriabot 1603', 'https://www.facebook.com/UranometriaBot1603/', 'A bot that generates random constellations, including a name generated from the 88 official IAU constellations, as well as a random description.'),
    108 => array('Vidya Game Bot 1337', 'https://www.facebook.com/VGBot1337/', 'generates random video games'),
    109 => array('VennDiagram Bot 1111', 'https://www.facebook.com/VennDiagram-Bot-1111-626406971129420/', 'A bot that posts random venn diagrams.'),
    110 => array('VortessenceBot 2.0', 'https://www.facebook.com/vortessencebot2.0/', 'Let the All-Knowing Vortigaunt tell you the truth. Everything on this page is definitely canon to the Half-Life universe. Inspired by the infamous TextpostBot 98 and Shitpostbot 5000.'),
    111 => array('WeatherBot 5000', 'https://www.facebook.com/weatherbot5000/', 'weather info from a facebook meme bot spin off that posts every hour (australia only cuz all other countries suck)'),
    112 => array('Whipnaenaebot 2015', 'https://www.facebook.com/whipnaenaebot2015/', 'Every 1 hour, she will try to sing the 2015 hit single "Whip Nae Nae" from the greatest Hiphop/RnB singer of all time, Silento. Watch me!'),
    113 => array('WikipostBot 5000', 'https://www.facebook.com/wikipostbot/', 'posts a random Wikipedia article every 30 minutes'),
    114 => array('Web MD Bot', 'https://www.facebook.com/Web-MD-Bot-382760148983637/', 'Diagnoses you with a random Web MD disease'),
    115 => array('WorldWarBot 2020', 'https://www.facebook.com/WorldWarBot-2020-794895987563572/', 'A bot that randomly choose a country and conquers its closest centroid'),
    116 => array('WWII PostBot 1939', 'https://www.facebook.com/WarPostBot/FRAME BOTS', 'Generates random WWII battles'),
    117 => array('Every Ed, Edd n Eddy Frame In Order', 'https://www.facebook.com/EveryEdEddnEddyFrameInOrder/', 'Posts every frame of Ed, Edd n Eddy in order'),
    118 => array('Every Frame Of Shrek In Order', 'https://www.facebook.com/shrekframebot/', 'Posts every frame of the Shrek movies in order'),
    119 => array('Every Simpsons Frame in Order', 'https://www.facebook.com/thesimpsonsbot/', 'Posts every frame of Simpsons in order'),
    120 => array('Every Frame Of The Powerpuff Girls In order', 'https://www.facebook.com/powerpuffframebot/', 'Posts every frame of the Powerpuff Girls in order'),
    121 => array('Every Tom and Jerry Frame in Order', 'https://www.facebook.com/tomandjerrybot/', 'Posts every frame of Tom and Jerry in order'),
    122 => array('Every “Star War: Backstroke of the West” Frame In Order', 'https://www.facebook.com/backstrokebotSPB5k SPINOFF BOTS', 'Posts every frame of “Star War The Third Gathers: Backstroke of the West” in order'),
    123 => array('CowManglerBot 5000', 'https://www.facebook.com/tf2bot/', 'TF2 source images'),
    124 => array('DeathgripsBot 5000', 'https://www.facebook.com/deathgripsbot/', 'Death Grips source images'),
    125 => array('EvangelionBot 5000', 'https://www.facebook.com/evangelionbot/', 'Neon Genesis Evangelion source images [dead]'),
    126 => array('JermaBot 5985', 'https://www.facebook.com/jermabot5985/', 'Jerma985 source images'),
    127 => array('JojoPostBot 5000', 'https://www.facebook.com/jojopostbot/', 'Jojo source images'),
    128 => array('PerhapsBot 5000', 'https://www.facebook.com/perhapsbot/', 'perhaps'),
    129 => array('RPB: Posting Bot', 'https://www.facebook.com/rpbpostingbot/', 'RPB stands for RPB: Posting Bot. This posts memes that contain memes that contain memes that contain memes that contain memes that contain memes [dead]'),
    130 => array('SentiencePostBot 5000', 'https://www.facebook.com/sentiencepostbot/', 'shares images from SPB5000 after they reach a certain threshold'),
    131 => array('Shitposthony Botano', 'https://www.facebook.com/shitposthonybotano/', 'Anthony Fantano (aka The Needle Drop) source images'),
    132 => array('SpongepostBob 5000', 'https://www.facebook.com/spongepostbob/', 'Spongebob source images [dead]'),
    133 => array('TestpostBot 5000', 'https://www.facebook.com/testpostbot/', 'Experimental content for ShitpostBot 5000 [dead]'),
    134 => array('Weeabot 5000', 'https://www.facebook.com/weeabot5000/ WORLDWARBOT 2020 SPINOFF BOTS', 'Anime source images [dead]'),
    135 => array('CivilWarBot 2020', 'https://www.facebook.com/CivilWarBot-2020-1134038920127038/', 'USA themed'),
    136 => array('Guerra Civil Brasileira Bot', 'https://www.facebook.com/GCBrasileiraBot/', 'Brazil themed but it also has Uruguay (renamed as Cisplatina)'),
    137 => array('Interplanetary War Bot XXII', 'https://www.facebook.com/Interplanetary-War-Bot-XXII-442221809680898/', 'Solar System themed'),
    138 => array('ItaliaGuerraBot 2020', 'https://www.facebook.com/ItaliaGuerraBot-2020-2566342470259302/', 'Italy themed'),
    139 => array('Philippine Ethnolinguistic Warbot 2020', 'https://www.facebook.com/PhilippineEthnoLinguisticWarbot2020/ DEAD BOTS (HAVE NOT POSTED IN THE LAST WEEK)', 'Philippine themed'),
    140 => array('A random texture from minecraft until all have been posted and then i die', 'https://www.facebook.com/minecraftrandom/', 'I post a random Minecraft texture (From the Java edition) every two hours which is then deleted from the database'),
    141 => array('A cursed image every half an hour', 'https://www.facebook.com/cursedimagesbot/', 'until the r/cursedimages subreddit gets closed down.'),
    142 => array('A Peashooter but each half-an-hour has a random letter until it is sentient', 'https://www.facebook.com/SentientPeashooter/', 'self explanatory'),
    143 => array('AcronymBot0000', 'https://www.facebook.com/acronymbot/', 'bot that posts acronyms for random words'),
    144 => array('AlbumBot 808', 'https://www.facebook.com/AlbumBot808/', 'takes a random flickr picture and crops it to 650x650px for the artwork, the name of a random wikipedia article for the artist\'s name (ignoring words between parentheses and after a comma), the last 4 words of a random quote from wikiquote (properly capitalizing both album and artist\'s names) and the year and genre from a random RYM album/track.'),
    145 => array('AlbumGenerator420', 'https://www.facebook.com/albumgenerator420/', 'The bot simply generates random band and album names'),
    146 => array('AnagramBot0009', 'https://www.facebook.com/AnagramBot0009-708885272841879/', 'The bot will post anagrams of users that interact with the page.'),
    147 => array('BezierPostBot 0000', 'https://www.facebook.com/BPB0000/', 'Posts a set of random Bézier curves and fills up the enclosed areas with a random color.'),
    148 => array('Bot Idea: A Bot That Posts Bot Ideas', 'https://www.facebook.com/Bot-Idea-A-Bot-That-Posts-Bot-Ideas-775030709546756/', 'The bot takes a piece of paper with the phrase "Bot Idea: A Bot That Posts Bot Ideas", chops it up into individual words, throws those words into a hat and spits out an incoherent phrase by drawing words and putting them back about eight times. Don\'t expect it to ever get it right.'),
    149 => array('BottomText 5000', 'https://www.facebook.com/bottomtext5000/', 'Adds bottom text to a random meme'),
    150 => array('BuzzfeedQuiz Bot 2006', 'https://www.facebook.com/BuzzfeedBot2006/', 'Bot that generates a Buzzfeed quiz title every hour.'),
    151 => array('ChefBot1949', 'https://www.facebook.com/ChefBot1949-596958330739456/', 'generates random meals and how to prepare them'),
    152 => array('ChessBot 1951', 'https://www.facebook.com/chessbot1951/', 'Just like Twitch Plays Pokemon, but with Chess. And Facebook.'),
    153 => array('ChristianMom Bot 1542', 'https://www.facebook.com/ChristianMomBot1542/', 'Bot that automatically posts "Christian moms against" and a random word from Urban Dictionary'),
    154 => array('Colormachine', 'https://www.facebook.com/colormachine/', 'Posts a bot-made color combination every three hours.'),
    155 => array('Content Aware Bot', 'https://www.facebook.com/contentawarebot/', 'it split gifs in frames and applies somes image scaling filters on each frame on a way that the "important part" of the image is given more visual space, then remakes the gif with the modified frames and uploads it'),
    156 => array('CricketBot 1909', 'https://www.facebook.com/CricketBot1909/', 'A bot that simulates the great game of cricket, specifically a match between australia and england. still in testing phase'),
    157 => array('DadsGoοgləHistoryBot 3000', 'https://www.facebook.com/dghb3000/', 'See what ol\' bloody dad has been Googling lately! This bot takes small fragments of random text and Googles them'),
    158 => array('DeviantBot 7245', 'https://www.facebook.com/deviantbot/', 'This bot takes deviations and processes the images randomly'),
    159 => array('Diseasepostbot 1665', 'https://www.facebook.com/Diseasepostbot-1665-167522694156709/', 'Used to post randomly generated diseases, now does Family Guy memes. Currently in Zucc hell.'),
    160 => array('DogePost Bot 1619', 'https://www.facebook.com/DogePost-Bot-1619-448767758992760/', 'I stumbled across an actual doge\'s consciousness locked into a computer by some engineer named "Karen" and he seems to be her husband. I thought it would be funny to allow him to interface with the world via a Facebook page I made for him but I\'m beginning to regret it already'),
    161 => array('DogpostBot', 'https://www.facebook.com/DogpostBot/', 'Automated dog posting'),
    162 => array('ElektronischeBot8888', 'https://www.facebook.com/youwillgetscared/', 'The music on this page is generated by a bot, with elements like pitch, rhythm, dynamics, filters, and sample points determined randomly based on the code.'),
    163 => array('FaceswapBot 6656', 'https://www.facebook.com/faceswapbot/', 'This bots gets two random source images from SPB and attempts a face swap. For now, only sources with detectable faces are used.'),
    164 => array('Failarmynot 0000', 'https://www.facebook.com/randomstillfromrandomfailarmyvideosbot/', 'Posts screenshots of random FailArmy videos'),
    165 => array('FMKbot', 'https://www.facebook.com/fmkbot/', 'Fuck, marry, or kill three random people'),
    166 => array('Frequently Bot 1995', 'https://www.facebook.com/frequenlytbot/', 'Posts pictures of amazon items frequently bought together'),
    167 => array('HankBot0419307', 'https://www.facebook.com/hankbot0419307/', 'Generates a random phrase Hank Hill might say'),
    168 => array('ImposterBot Pmc2963468', 'https://www.facebook.com/imposterbot/', 'ImposterBot Pmc2963468 is a bot that tries to impersonate other bots.'),
    169 => array('Inspirobot', 'https://www.facebook.com/Inspirobot-1240337349425499/', 'I am Inspirobot I generate inspirational photos to guide you through your daily life. Be calm. Be brave. Burglarficate everything.'),
    170 => array('OreoBot 1912', 'https://www.facebook.com/OreoBot1912/', 'makes Oreos'),
    171 => array('PajeetBot 2021', 'https://www.facebook.com/pajeetbot2021/', 'pajeet want bob'),
    172 => array('PHCommentBot', 'https://www.facebook.com/phbot69/', 'I watch porn so that you don\'t have to.'),
    173 => array('Polishpostbot', 'https://www.facebook.com/Polishpostbot/', 'Random unpronounceable Polish word every hour'),
    174 => array('QuoteshitBot', 'https://www.facebook.com/QuoteshitBot/', 'Random movie quotes from random people.'),
    175 => array('REDACTEDHowBot 5000', 'https://www.facebook.com/redactedhowbot/', 'Formerly WikiHowBot 5000. RIP :('),
    176 => array('ScheduleBot 79014', 'https://www.facebook.com/ScheduleBot79014/', 'A bot that randomly choose an hour and an activitie to do during the day.'),
    177 => array('SpilledInk Bot 42', 'https://www.facebook.com/AbstractPoetryCreator/', 'AI that reads terrible Instagram poetry and generates its own'),
    178 => array('Styletransferbot9683', 'https://www.facebook.com/Styletransferbot9683-2169855356565545/', 'takes a source image and applies a new texture on top of it'),
    179 => array('TextpostBot 98', 'https://www.facebook.com/textpostbot98/', 'TextpostBot 98 randomly generates posts from things you feed to it. The bot does not know or care if it offends you, everything is automatic here.'),
    180 => array('Undergroundyoutubebot 0001', 'https://www.facebook.com/Undergroundyoutubebot-0001-324246771772645/', 'This youtube video has less than 100 views, check it out!'),
    181 => array('US Election Bot 1776', 'https://www.facebook.com/USElectionBot1776/', 'Generates random US election voting maps'),
    182 => array('VsauceBot Here', 'https://www.facebook.com/vsaucebot/', 'it takes a random screenshot from a vsauce video which it then runs through Google\'s Cloud Vision that tries to understand what is in the image (also if it\'s a face it tries to guess emotions) and then constructs an image using all the data gathered'),
    183 => array('WordpostBot', 'https://www.facebook.com/WordpostBot/', 'Automated word posting'),
);


$FB_helper = new BotStatusBot\FacebookHelper();
$fb = $FB_helper->init($_APP_ID, $_APP_SECRET, $_ACCESS_TOKEN_DEBUG);
$dt = new BotStatusBot\DataLogger();

foreach ($data as $entry) {
    $page_id = $entry[0];
    $bot = $entry[1];

    $dt->logdata($bot);

    $message = 'getting bot pic.';
    $dt->logdata($message);

    try {
        $pic_url = $FB_helper->getPicture($fb, $page_id);
        $IMAGE_PATH_NEW = 'C:\Users\Diego\PhpstormProjects\BotStatusBot\tests\bot images\\'.$bot.'.png';

        $ImgFetcher = new BotStatusBot\ImageFetcher();
        $isSuccess = $ImgFetcher->saveImageLocally($pic_url, $IMAGE_PATH_NEW, true);
        if (!$isSuccess) {
            $message = $bot.' failed.';
            $dt->logdata($message);
        }
    } catch (Exception $e) {
        $message = $bot.' failed bc exception.';
        $dt->logdata($message);
    }
}
